# Generated by Django 6.1.1 on 2026-10-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='pdf_text',
            field=models.TextField(blank=True),
        ),
    ]
